language: python
python:
- 3.6
notifications:
  email: false
  webhooks: https://coveralls.io/webhook
  slack:
    secure: QshUa/5NpsPSu8DlOS3VtpxcV2ijiXsRGKTR7AFn53vIaZaZ/0hTLJLpf+cz3E73kpMbj75jFGu54habUm3+SlHHQm60iJ+A8QHg625R9yp7x8A3Yv2KrrYsVrOHFoEmQQ60aDrS/MtxLd6yCr5sSyZdEedhhetkSlr6t+Mz8pxeWL8S/iuA3nkVUWzLyXtf59PpaVg3FkcrWNOsjXz6m1QlyvX1ZeDeLSm3Ag3hW2aJDcJWXj7mlSX4wwwgYkj8FJLTmzAMjN7BOQA2txe+G5TjS/bl6UEo5hNPUVJ6fa4IpU/saafsqVy5kOvDHxPXKJsFGBS4vTQAQzPrAG4tFZL+LO/X4cCyQtsXiUsIMP8oQ0yg2qdBgbQsmBpDVj/sp+5kuCJVd9W6OPupiQ53INllp019nMzqiqjGtylHhxFHi8X5V89LBdN9ajMCVkxbfUTcM/jUqJoCfPntD+3nZHu3VTgDka0vVY+gQDFHJnAew/n4hbYx4qoleAiOxh6eXJ8fRQwNO7R0L6gdFxqVvZ69fKDUlMnzCqGMwI0s4mjDQ8duNSUPf6t1k+u0U9HzV9BKBiGnBIUw2s1YcALILggUQT4B+5rRmeoTx5+mOXGI3IPbUpcNuAMstO/vAG+Ub4mY+w0dhabNtTb2oPD6PBe4SRcEggB3EU8Qd/3xpkA=
sudo: false
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- if [ -x ${HOME}/miniconda3/pkgs ]; then pushd ${HOME}/miniconda3/pkgs && find -maxdepth 1 -mindepth 1 -type d | xargs rm -rf && popd; fi
- chmod +x miniconda.sh
- ./miniconda.sh -b -f
- ${HOME}/miniconda3/bin/conda update conda --yes

install:
- ${HOME}/miniconda3/bin/conda env create -f environment.yaml -n parserdev -v
- ${HOME}/miniconda3/envs/parserdev/bin/pip install -e .
- echo "import os" > sitecustomize.py
- echo "try:" >> sitecustomize.py
- echo "    import coverage" >> sitecustomize.py
- echo "    os.environ['COVERAGE_PROCESS_START'] = '.coveragerc'" >> sitecustomize.py
- echo "    coverage.process_startup()" >> sitecustomize.py
- echo "except ImportError:" >> sitecustomize.py
- echo "    pass" >> sitecustomize.py

script:
- ${HOME}/miniconda3/envs/parserdev/bin/nosetests --nologcapture tests --with-coverage --cover-package rstfinder --cov-config .coveragerc

after_success:
- ${HOME}/miniconda3/envs/parserdev/bin/coveralls
